version: '3'
services:
  app-one:
    image: kafka-adapter
    ports:
      - '9000:5000'
    depends_on:
      - redis
  app-two:
    image: kafka-adapter
    ports:
      - '8000:5000'
    depends_on:
      - redis
  redis:
    image: redis
